### ISSUE TITLE
Article classifications

### ISSUE THREAD

**Issue by adamhsparks** [phytopathology/Reproducible.Plant.Pathology#10]
Articles will be classified by the evaluator as to whether they are:
  - Fundamental research  
  - Applied research  
  - Molecular research  
  - Combined  

Is there another classification that you would like to use or are these three (or a combination of) enough?

**Comment by zachary-foster** [comment]
Its hard to say. I expect that we will come up with more and we will need to combine some of them. For example (Molecular and Applied/Fundamental). What if we just treated them like "tags" and made up ones as seems appropriate at the time and then try to consolidated shared themes into categories at the end or only use the most commonly used tags? Alternatively, we could have some master list and add to it if we think of a new category. If someone else added a similar category we just use that instead.

**Comment by adamhsparks** [comment]
I'm thinking that some sort of master list makes it easier to assemble at the end.
