### ISSUE TITLE
Getting the references into our tidy data frame in R

### ISSUE THREAD

**Issue by adamhsparks** [phytopathology/Reproducible.Plant.Pathology#8]
I did some checking, we can save ourselves some typing.

[Zotero](https://www.zotero.org) will export a CSV file of a .bib file. We can import that into R and select the columns that we need from that file. That should greatly simplify our typing data in and cut down on possible data entry errors.

JabRef will do this too, but doesn't appear to export the DOI field.

**Comment by zachary-foster** [comment]
Sounds great!

**Comment by emdelponte** [comment]
Here is what I have used in one of my projects to produce authorship network and word cloud.

Mendeley -> XML -> R data frame

library(XML)
sad_xml<-xmlParse("conferido.xml")
sad <- xmlToDataFrame(nodes = getNodeSet(sad_xml, "//record"))

**Comment by adamhsparks** [comment]
Automated using `bib2df` and searching for DOI for bib entries.

Will manually enter values that the DOI search doesn't find in the Google Sheets.
